document.write('<!doctype html>');
document.write('<html lang="en">');
document.write('');
document.write('<head>');
document.write('  <meta charset="utf-8">');
document.write('  <title>PluggedIn</title>');
document.write('  <base href="/">');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1">');
document.write('  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>');
document.write('  <link rel="icon" type="image/x-icon" href="favicon.ico">');
document.write('  <style>');
document.write('    .floating-section {');
document.write('      position: fixed;');
document.write('      z-index: 4;');
document.write('      bottom: 0;');
document.write('    }');
document.write('');
document.write('    .floating-chat {');
document.write('      border-radius: 22%;');
document.write('      height: 9vh;');
document.write('      aspect-ratio: 1 / 1;');
document.write('      animation: 3s linear 0s infinite alternate slidein;');
document.write('    }');
document.write('');
document.write('    @keyframes slidein {');
document.write('      from {');
document.write('        transform: translateX(100vw) scale(1, 1);');
document.write('        -webkit-backface-visibility: hidden;');
document.write('      }');
document.write('');
document.write('      to {');
document.write('        transform: translateX(90vw) scale(1, 1);');
document.write('        -webkit-backface-visibility: hidden;');
document.write('      }');
document.write('    }');
document.write('');
document.write('    .iframe-cls {');
document.write('      position: fixed;');
document.write('      bottom: 0;');
document.write('      right: 0;');
document.write('      z-index: 5;');
document.write('      width: 28%;');
document.write('      border: 2px solid black;');
document.write('    }');
document.write('  </style>');
document.write('</head>');
document.write('');
document.write('<body>');
document.write('  <script type="text/javascript">');
document.write('    var openEnderContent = "<iframe width=\\\'1080\\\' height=\\\'760\\\' class = \'iframe-cls\' src=\'https://demo.infinitepossibilities.ai/\' frameborder=\'0\' allowfullscreen></iframe>";');
document.write('    function demoOpen() {');
document.write('      $(document).ready(function () {');
document.write('        $(\'#iframe-show\').html(openEnderContent);');
document.write('      });');
document.write('    }');
document.write('  </script>');
document.write('  <div class="floating-section floating-chat " style="display:flex;text-align: center;padding:5px;background: aquamarine;" onclick=" return demoOpen()">');
document.write('  <p class="img-fluid " style="margin-top: 20px;">Chat with us!</p>');
document.write('   <svg  class="img-fluid " xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M7.29117 20.8242L2 22L3.17581 16.7088C2.42544 15.3056 2 13.7025 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C10.2975 22 8.6944 21.5746 7.29117 20.8242Z"></path></svg>');
document.write('  </div>');
document.write('  <div id="iframe-show"> </div>');
document.write('</body>');
document.write('');
document.write('</html>');
